VERSION = "2.0.0"

[DOCUMENTATION]
ORG_NAME = "Laam Project"
ORG_URL = "https://laam.online"
ORG_DESCRIPTION = "Laam is a native token built on the Stellar blockchain for decentralized financial use cases."
ORG_LOGO = "https://fond-magenta-owpureihfj.edgeone.app/20250802_225108.png"

[[CURRENCIES]]
code = "LAAM"
issuer = "GAL4ECDAXNBMJYFCWIJ32HKVIRLCNEXY664CAZYI3EINQWPLXTMEPR64"
display_decimals = 2
name = "Laam Coin"
desc = "Laam Coin is a Stellar-based token with a fixed supply of 1,335,577, created to support accessible DeFi use cases."
image = "https://fond-magenta-owpureihfj.edgeone.app/20250802_225108.png"
